title: housematee-tgbot
production: false

telegram:
  api_token: {{housematee-tgbot.telegram.api_token}}}
  allowed_channels: {{housematee-tgbot.telegram.allowed_channels}}}

google_apis:
  credentials:
    client_email: {{housematee-tgbot.google_apis.credentials.client_email}}}
    private_key: {{housematee-tgbot.google_apis.credentials.private_key}}}
    token_uri: {{housematee-tgbot.google_apis.credentials.token_uri}}}

google_sheets:
  spreadsheet_id: {{housematee-tgbot.google_sheets.spreadsheet_id}}}
